/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterRegisterRouteImport } from './routes/register/register'
import { Route as RegisterLoginRouteImport } from './routes/register/login'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRegisterRoute = RegisterRegisterRouteImport.update({
  id: '/register/register',
  path: '/register/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterLoginRoute = RegisterLoginRouteImport.update({
  id: '/register/login',
  path: '/register/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/register/login': typeof RegisterLoginRoute
  '/register/register': typeof RegisterRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/register/login': typeof RegisterLoginRoute
  '/register/register': typeof RegisterRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/register/login': typeof RegisterLoginRoute
  '/register/register': typeof RegisterRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/register/login' | '/register/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/register/login' | '/register/register'
  id: '__root__' | '/' | '/about' | '/register/login' | '/register/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RegisterLoginRoute: typeof RegisterLoginRoute
  RegisterRegisterRoute: typeof RegisterRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/register': {
      id: '/register/register'
      path: '/register/register'
      fullPath: '/register/register'
      preLoaderRoute: typeof RegisterRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/login': {
      id: '/register/login'
      path: '/register/login'
      fullPath: '/register/login'
      preLoaderRoute: typeof RegisterLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RegisterLoginRoute: RegisterLoginRoute,
  RegisterRegisterRoute: RegisterRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
